### PR TITLE
Removed unused parameter

### PR DESCRIPTION
**Pull request by jgmGit**
Removed unused parameter causing compiler warnings

### CODE REVIEW

**Review by jpnurmi — APPROVED** [review]
Thanks, LGTM :+1:

**Comment by jgmGit** [comment]
@jpnurmi Is a release upcoming ? Any ETA for this ? Wanted to use it in my project.

**Comment by jpnurmi** [comment]
Thanks for the fix. I've published v0.1.5.

**Comment by jgmGit** [comment]
Thanks a lot

**Pull request merged**
