### PR TITLE
Compile stylesheet using sass

### PR DESCRIPTION
**Pull request by Jupi007**
Simplify stylesheet maintaining using sass.
No design change.

### CODE REVIEW

**Comment by Jupi007** [comment]
The CI fails, but it doesn't look related to my changes.

**Comment by Feichtmeier** [comment]
Sorry but I can not review this since my knowledge of this repo is very limited

**Comment by jpnurmi** [comment]
@Jupi007 What sass version do you have?

```
$ ./assets/compile.sh 
Compile handy-window.scss
OptionParser::InvalidOption: invalid option: --no-source-map
Did you mean?  sourcemap
  Use --trace for backtrace.
Compile handy-window-dark.scss
OptionParser::InvalidOption: invalid option: --no-source-map
Did you mean?  sourcemap
  Use --trace for backtrace.
Done
```
```
$ sass --version
Ruby Sass 3.7.4
```
```
$ apt info ruby-sass
Package: ruby-sass
Version: 3.7.4-5
Priority: optional
Section: universe/ruby
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian Ruby Team <pkg-ruby-extras-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1.002 kB
Provides: sass
Depends: ruby, ruby-listen (>= 3.0)
Breaks: ruby-sass-rails (<< 5~)
Homepage: https://sass-lang.com/
Ruby-Versions: all
Download-Size: 179 kB
APT-Manual-Installed: yes
APT-Sources: http://dk.archive.ubuntu.com/ubuntu kinetic/universe amd64 Packages
Description: deprecated CSS compiler - use sassc or ruby-sassc instead
 Sass makes CSS fun again. Sass is an extension of CSS3, adding nested
 rules, variables, mixins, selector inheritance, and more.
 .
 It's translated to well-formatted, standard CSS using the command line
 tool or a web-framework plugin.
 .
 Ruby Sass should no longer be used and will no longer be receiving any
 active development. Please use sassc or ruby-sassc instead.

```

**Comment by Jupi007** [comment]
@jpnurmi I'm using dart-sass `1.57.1` which is the official implementation of the scss compiler, your version is ruby-sass and it is abandoned :)
You can install it with npm:
```
sudo npm install -g sass
```
Note: remove the apt version before install the npm version.

**Comment by Jupi007** [comment]
> Sorry but I can not review this since my knowledge of this repo is very limited

@Feichtmeier I was request your review on the scss/css part, because it is the only part I modified :D
But anyway, I also need @jpnurmi opinion on this.

**Comment by jpnurmi** [comment]
Thanks, I'll try to install sass via npm. For what it's worth, I like the idea. The less we deviate from upstream the better.

**Comment by jpnurmi** [comment]
Can I install npm using apt or is it also too old? :D

**Comment by jpnurmi** [comment]
I get `rgba(0,0,0,0)` instead of `transparent` :thinking: 

```diff
$ sass --version
1.57.1 compiled with dart2js 2.18.6
$ ./compile.sh 
Compile handy-window.scss
Compile handy-window-dark.scss
Done
$ git status
On branch use-scss
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   handy-window-dark.css

no changes added to commit (use "git add" and/or "git commit -a")
```
```diff
diff --git a/assets/handy-window-dark.css b/assets/handy-window-dark.css
index a292da5..3cb0047 100644
--- a/assets/handy-window-dark.css
+++ b/assets/handy-window-dark.css
@@ -1 +1 @@
-window.csd.unified:not(.solid-csd):not(.fullscreen):not(.maximized) decoration-overlay{box-shadow:inset 0 0 0 1px rgba(255,255,255,.07)}window.csd.unified:not(.solid-csd):not(.fullscreen):not(.maximized) headerbar{box-shadow:none}decoration{box-shadow:0 3px 9px 1px rgba(0,0,0,.5)}decoration:backdrop{box-shadow:0 3px 9px 1px transparent,0 2px 6px 2px rgba(0,0,0,.2)}
+window.csd.unified:not(.solid-csd):not(.fullscreen):not(.maximized) decoration-overlay{box-shadow:inset 0 0 0 1px rgba(255,255,255,.07)}window.csd.unified:not(.solid-csd):not(.fullscreen):not(.maximized) headerbar{box-shadow:none}decoration{box-shadow:0 3px 9px 1px rgba(0,0,0,.5)}decoration:backdrop{box-shadow:0 3px 9px 1px rgba(0,0,0,0),0 2px 6px 2px rgba(0,0,0,.2)}
```

**Comment by Jupi007** [comment]
> Can I install npm using apt or is it also too old? :D

There is a very nice snap package for node and npm: https://snapcraft.io/node :D

> I get `rgba(0,0,0,0)` instead of `transparent` thinking

Indeed, me too. In fact I just updated sass and now the output is different.
`rgba(0,0,0,0)` and `transparent` are the same, the rgba version can even be more appropriated because of the property transition (as it is a fully transparent black, and not just transparent empty colour).
I will commit it so :)

**Review by jpnurmi — APPROVED** [review]
Great! Compiles without local modification now. LGTM :+1:

**Pull request merged**
