### PR TITLE
Fix libhandy_window_plugin.so's RUNPATH

### PR DESCRIPTION
**Pull request by jpnurmi**
This ensures that it will find `libhandy_flutter.so`:

```
$ objdump -p build/linux/x64/release/bundle/lib/libhandy_window_plugin.so
...
Dynamic Section:
  NEEDED               libhandy_flutter.so
  ...
  SONAME               libhandy_window_plugin.so
  RUNPATH              $ORIGIN
  ...
```

### CODE REVIEW

**Comment by Feichtmeier** [comment]
Looking good

```
frederik@carbon:~/Projects/software/build/linux/x64/release/bundle$ objdump -p lib/libhandy_window_plugin.so

lib/libhandy_window_plugin.so:     Dateiformat elf64-x86-64

Programm-Header:
    LOAD off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**12
         filesz 0x0000000000001618 memsz 0x0000000000001618 flags r--
    LOAD off    0x0000000000002000 vaddr 0x0000000000002000 paddr 0x0000000000002000 align 2**12
         filesz 0x0000000000000f39 memsz 0x0000000000000f39 flags r-x
    LOAD off    0x0000000000003000 vaddr 0x0000000000003000 paddr 0x0000000000003000 align 2**12
         filesz 0x0000000000000790 memsz 0x0000000000000790 flags r--
    LOAD off    0x0000000000003c90 vaddr 0x0000000000004c90 paddr 0x0000000000004c90 align 2**12
         filesz 0x0000000000000528 memsz 0x0000000000000560 flags rw-
 DYNAMIC off    0x0000000000003cd0 vaddr 0x0000000000004cd0 paddr 0x0000000000004cd0 align 2**3
         filesz 0x0000000000000310 memsz 0x0000000000000310 flags rw-
    NOTE off    0x0000000000000238 vaddr 0x0000000000000238 paddr 0x0000000000000238 align 2**2
         filesz 0x0000000000000024 memsz 0x0000000000000024 flags r--
EH_FRAME off    0x00000000000032f0 vaddr 0x00000000000032f0 paddr 0x00000000000032f0 align 2**2
         filesz 0x00000000000000a4 memsz 0x00000000000000a4 flags r--
   STACK off    0x0000000000000000 vaddr 0x0000000000000000 paddr 0x0000000000000000 align 2**4
         filesz 0x0000000000000000 memsz 0x0000000000000000 flags rw-
   RELRO off    0x0000000000003c90 vaddr 0x0000000000004c90 paddr 0x0000000000004c90 align 2**0
         filesz 0x0000000000000370 memsz 0x0000000000000370 flags r--

Dynamischer Abschnitt:
  NEEDED               libhandy_flutter.so
  NEEDED               libflutter_linux_gtk.so
  NEEDED               libblkid.so.1
  NEEDED               liblzma.so.5
  NEEDED               libgtk-3.so.0
  NEEDED               libgdk-3.so.0
  NEEDED               libpangocairo-1.0.so.0
  NEEDED               libpango-1.0.so.0
  NEEDED               libharfbuzz.so.0
  NEEDED               libatk-1.0.so.0
  NEEDED               libcairo-gobject.so.2
  NEEDED               libcairo.so.2
  NEEDED               libgdk_pixbuf-2.0.so.0
  NEEDED               libgio-2.0.so.0
  NEEDED               libgobject-2.0.so.0
  NEEDED               libglib-2.0.so.0
  NEEDED               libstdc++.so.6
  NEEDED               libm.so.6
  NEEDED               libgcc_s.so.1
  NEEDED               libc.so.6
  SONAME               libhandy_window_plugin.so
  RUNPATH              $ORIGIN
  INIT                 0x0000000000002000
  FINI                 0x0000000000002f2c
  INIT_ARRAY           0x0000000000004c90
  INIT_ARRAYSZ         0x0000000000000008
  FINI_ARRAY           0x0000000000004c98
  FINI_ARRAYSZ         0x0000000000000008
  GNU_HASH             0x0000000000000260
  STRTAB               0x0000000000000850
  SYMTAB               0x0000000000000298
  STRSZ                0x00000000000006c9
  SYMENT               0x0000000000000018
  PLTGOT               0x0000000000005000
  PLTRELSZ             0x00000000000004b0
  PLTREL               0x0000000000000007
  JMPREL               0x0000000000001168
  RELA                 0x0000000000001018
  RELASZ               0x0000000000000150
  RELAENT              0x0000000000000018
  VERNEED              0x0000000000000f98
  VERNEEDNUM           0x0000000000000003
  VERSYM               0x0000000000000f1a
  RELACOUNT            0x0000000000000006

Versionsreferenzen:
  von libgcc_s.so.1 benötigt:
    0x0b792650 0x00 06 GCC_3.0
  von libc.so.6 benötigt:
    0x09691a75 0x00 05 GLIBC_2.2.5
  von libstdc++.so.6 benötigt:
    0x056bafd3 0x00 04 CXXABI_1.3
    0x0297f864 0x00 03 GLIBCXX_3.4.14
    0x08922974 0x00 02 GLIBCXX_3.4
```

runpath is $ORIGIN
this is what we want, right?

**Comment by jpnurmi** [comment]
Yeah! One quick way to test is to rename `build/` after `flutter build linux` and then try to run the app.

**Comment by Feichtmeier** [comment]
grafik
Works for me (tm)

**Review by Feichtmeier — APPROVED** [review]

**Comment by jpnurmi** [comment]
Yay! :tada: Thanks for testing and confirming!

**Pull request merged**
